# Generated by Django 3.0.7 on 2020-07-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
