# Generated by Django 3.0.8 on 2020-07-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='num_work_days',
            field=models.IntegerField(),
        ),
    ]
