# Generated by Django 3.0.8 on 2020-07-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20200721_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='provider_range',
        ),
        migrations.AddField(
            model_name='location',
            name='provider_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='provider_min',
            field=models.IntegerField(default=0),
        ),
    ]
