# Generated by Django 3.0.8 on 2020-07-22 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20200721_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='num_work_days',
            new_name='days_per_week',
        ),
        migrations.CreateModel(
            name='ProviderVacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_date', models.DateField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderLocationMax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_location_max', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Location')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Provider')),
            ],
        ),
    ]
