# Generated by Django 3.0.8 on 2020-07-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20200721_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='provider_max',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='provider_min',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='provider',
            name='days_per_week',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='providerlocationmax',
            name='provider_location_max',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
