# Generated by Django 3.0.8 on 2020-07-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20200721_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='abbrev',
            field=models.CharField(max_length=5),
        ),
    ]
