# Generated by Django 3.0.8 on 2020-07-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20200721_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='abbrev',
            field=models.CharField(max_length=3),
        ),
    ]
