# Generated by Django 3.0.8 on 2020-07-22 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_auto_20200721_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerlocationmax',
            name='provider_location_max',
        ),
        migrations.AddField(
            model_name='providerlocationmax',
            name='provider_at_location_max_days',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
