# Generated by Django 3.0.8 on 2020-07-24 11:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_auto_20200722_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderLocationMaxForm',
            fields=[
                ('provider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduler.Provider')),
            ],
            bases=('scheduler.provider',),
        ),
        migrations.AlterField(
            model_name='provider',
            name='abbrev',
            field=models.CharField(error_messages={'unique': 'This abbreviation is already registered.'}, max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='providerlocationmax',
            name='provider_at_location_max_days',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
