# Generated by Django 3.0.8 on 2020-07-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_auto_20200724_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='abbrev',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='abbrev',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
